[package]
name = "core-data"
version = "0.1.0"
edition = "2021"
exclude = ["/xsd", "/xml", ".DS_Store", "/target", ".vscode", "generate.sh"]
authors = ["Harishankar Narayanan <nharishankar@gmail.com>"]
license = "Apache-2.0"
description = "Open Payments - Payment Processor"
readme = "../README.md"
homepage = "https://github.com/Open-Payments/messages"
repository = "https://github.com/Open-Payments/messages"
keywords = ["financial", "payments", "message", "iso20022", "processor"]
categories = ["data-structures", "development-tools", "finance", "parsing", "parser-implementations"]

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde-xml-rs = "0.6"
time = { version = "0.3.36", features = ["serde", "formatting", "parsing"] }
sonyflake = "0.3"
datalogic-rs = "1.0.2"
open-payments-common = { version = "1.0.8" }
open-payments-iso20022 = { version = "1.0.8", features = ["pacs", "pain", "head", "camt", "derive_serde"] }
serde_path_to_error = "0.1"
quick-xml = { version = "0.31", features = ["serialize"] }
